
export const LOADING = 'LOADING';

export const GET_PATIENT_SUCCESS = 'GET_PATIENT_SUCCESS';
export const GET_PATIENT_FAILED = 'GET_PATIENT_FAILED';

export const GET_PATIENTS_SUCCESS = 'GET_PATIENTS_SUCCESS';
export const GET_PATIENTS_FAILED = 'GET_PATIENTS_FAILED';

export const REMOVE_PATIENT_SUCCESS = 'REMOVE_PATIENT_SUCCESS';
export const REMOVE_PATIENT_FAILED = 'REMOVE_PATIENT_FAILED';

export const ADD_PATIENT_SUCCESS = 'ADD_PATIENT_SUCCESS';
export const ADD_PATIENT_FAILED = 'ADD_PATIENT_FAILED';

export const EDIT_PATIENT_SUCCESS = 'EDIT_PATIENT_SUCCESS';
export const EDIT_PATIENT_FAILED = 'EDIT_PATIENT_FAILED';