export const LOADING = 'LOADING';

export const GET_APPOINTMENT_SUCCESS = 'GET_APPOINTMENT_SUCCESS';
export const GET_APPOINTMENT_FAILED = 'GET_APPOINTMENT_FAILED';

export const GET_APPOINTMENTS_SUCCESS = 'GET_APPOINTMENTS_SUCCESS';
export const GET_APPOINTMENTS_FAILED = 'GET_APPOINTMENTS_FAILED';

export const REMOVE_APPOINTMENT_SUCCESS = 'REMOVE_APPOINTMENT_SUCCESS';
export const REMOVE_APPOINTMENT_FAILED = 'REMOVE_APPOINTMENT_FAILED';

export const ADD_APPOINTMENT_SUCCESS = 'ADD_APPOINTMENT_SUCCESS';
export const ADD_APPOINTMENT_FAILED = 'ADD_APPOINTMENT_FAILED';

export const EDIT_APPOINTMENT_SUCCESS = 'EDIT_APPOINTMENT_SUCCESS';
export const EDIT_APPOINTMENT_FAILED = 'EDIT_APPOINTMENT_FAILED';